### PR TITLE
Remove Link on Post Meta Date

### LINKED ISSUE #504: Single posts links to themselves
**Description**
In the single post view, the post date is linked to the current post. 

**Step-by-step reproduction instructions**
Open a single post on the front.
Confirm that the date is linked to the post.

**Expected behavior**
For a page to not link to itself.

### PR DESCRIPTION
**Pull request by bobmatyas**
**Description**

Removes date link from post meta template. Fixes https://github.com/WordPress/twentytwentyfour/issues/504

**Screenshots**

After:

Screenshot 2023-09-25 at 9 03 18 PM

**Testing Instructions**

1. Checkout PR and test.

**Contributors**

### CODE REVIEW

**Comment by carolinan** [comment]
Hi
This removes the link also from archives. So when a post has no title, there is no way to reach that post from the archive.

**Comment by bobmatyas** [comment]
Ahh shoot, I didn't test that scenario. I'll look at adding a conditional check and submitting a revised PR tomorrow.

**Comment by luminuu** [comment]
I'm not sure if this makes sense to put in a conditional there or if this should be an option on the post date block itself, which then has to be raised in the Gutenberg repo.

**Comment by carolinan** [comment]
There are different ways to solve this; these are my suggestions for short-term solutions, either:
- Use two different parts for the post meta. (Like one for archives, one for single)
- Remove the link from all post dates and add a read more block to the queries.

The reason why I recommend the first is because it could also be the best solution for this issue: https://github.com/WordPress/twentytwentyfour/issues/502

Long term, I am not sure that adding another condition to the control for the block would be best because it may be confusing to some users; maybe under advanced.

**Comment by MaggieCabrera** [comment]
> There are different ways to solve this; these are my suggestions for short-term solutions, either:
> 
>     * Use two different parts for the post meta. (Like one for archives, one for single)
> 
>     * Remove the link from all posts and add a read more block to the queries.
> 
> 
> The reason why I recommend the first is because it could also be the best solution for this issue: #502
> 
> Long term, I am not sure that adding another condition to the control for the block would be best because it may be confusing to some users; maybe under advanced.

On the other hand, having a read more link seems more intuitive than having the date be the link. I'd solve the post-meta problem using a pattern and a template part on that offending template. Having two identical template parts seems confusing and the user won't know right away which templates use which without having to check each one of them

**Comment by carolinan** [comment]
@MaggieCabrera @beafialho Is there a new design that includes a read more / continue reading?

**Comment by beafialho** [comment]
Yes, here's the design:

Captura de ecrã 2023-10-03, às 12 19 49

`Read More →` uses the same font size as post meta.

It can be seen on Figma [here](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=492-1806&mode=design&t=Tcut1PnuNtj2kWTw-4).

**Comment by carolinan** [comment]
So the meta is now above the excerpt, not below?

**Comment by beafialho** [comment]
It's always been, no? As seen [here](http://2024.wordpress.net/index.php/writer-home/).

**Comment by carolinan** [comment]
Only one some of the post lists.

**Comment by luminuu** [comment]
Carolina is refering to this pattern that is used with the business/entrepreneur home page, where the post meta is coming after the excerpt:

CleanShot 2023-10-04 at 13 30 02@2x

**Comment by MaggieCabrera** [comment]
The post meta is used in a lot of places, I think we can keep everything where it is and implement the read more link like on the screenshot Bea provided without altering any of the other blocks. The arrow can be implemented in a similar way that I did with the block style for nav link items (it's a different arrow there, but the implementation should be very similar if not the same)

**Comment by richtabor** [comment]
I'm going to close this. I agree, we should keep a consistent post-meta across the board; as we're using it in template part fashion. Makes it much easier to change from the user's perspective wherever it's used.

**Pull request closed without merging**
