### PR TITLE
Add image license

### PR DESCRIPTION
**Pull request by carolinan**
**Description**
Adds image license and image source links to the readme.txt file.

Partial for https://github.com/WordPress/twentytwentyfour/issues/364
I did not add the images that are removed in https://github.com/WordPress/twentytwentyfour/pull/459

@beafialho What is the license and source of icon-message.webp ?

### CODE REVIEW

**Comment by kafleg** [comment]
I think we also need to add, https://www.rawpixel.com/services/licenses 
This link is for raw pixel image license.

**Comment by carolinan** [comment]
I think that may be confusing since it includes more than one licence type and the theme is only using one'?

**Comment by beafialho** [comment]
@carolinan the `icon-message.webp` is a unicode symbol which was exported as an image.

**Comment by carolinan** [comment]
I have never tried to look up licensing for unicode.. is it this? https://www.unicode.org/license.txt From https://www.unicode.org/policies/licensing_policy.html

**Comment by beafialho** [comment]
> I have never tried to look up licensing for unicode

Me neither, but this seems to be it yes.

**Comment by luminuu** [comment]
@carolinan Can this PR be merged or do you want to add the remaining image licenses from stocksnap.io here too?

**Comment by carolinan** [comment]
@luminuu It can be merged, there are two PR's to remove those images

**Review by luminuu — APPROVED** [review]
LGTM

**Pull request merged**
