### PR TITLE
Update Contributors list

### PR DESCRIPTION
**Pull request by MaggieCabrera**
**Description**

Let's make sure we are not missing anyone from this list ahead of RC1. @gregoryfu and @benharri can you please share your wordpress.org profile usernames?

### CODE REVIEW

**Comment by gregoryfu** [comment]
My wordpress.org profile name is @gregfuller. Thanks.

**Comment by gregoryfu** [comment]
My wordpress.org username is gregfuller. Thanks.

**Comment by huzaifaalmesbah** [comment]
@michaelshowes @Ren2049 can you please share your wordpress.org profile username?

**Comment by benharri** [comment]
same as here, benharri

**Pull request closed without merging**
