### PR TITLE
Bring back translations to the pricing pattern

### PR DESCRIPTION
**Pull request by juanfra**
**Description**

- Bring back translations to the pricing pattern.

### CODE REVIEW

**Comment by richtabor** [comment]
Solid, but do want to note that there are still changes that may land. We're starting to get solid on the design system (esp if/when fluid type scale https://github.com/WordPress/twentytwentyfour/pull/268 lands). Mind taking a look at that?

**Comment by carolinan** [comment]
I honestly don't understand why changes to the design system keeps removing the translations... 
Example: Changing a size preset on a wrapping group block in a pattern should not change any text at all, only the small part of the pattern that *needs* to be changed, should be changed.

**Comment by richtabor** [comment]
> I honestly don't understand why changes to the design system keeps removing the translations...

Because we're not just changing one or two values; they are more substantial. So we're having to copy/paste the new pattern code into the PHP file, then add back all the translation functions. It's quite time-consuming and slows down the iterative process. 

About half of the patterns are solid; will less possible changes — but the other half still need a good bit of re-working. If you look at the patterns in the library, you can tell them apart well.

**Comment by juanfra** [comment]
> Solid, but do want to note that there are still changes that may land. We're starting to get solid on the design system (esp if/when fluid type scale https://github.com/WordPress/twentytwentyfour/pull/268 lands). Mind taking a look at that?

Sure, will do 🎉

**Review by carolinan — APPROVED** [review]

**Pull request merged**
