### PR TITLE
Added Translation code to Project Details pattern

### PR DESCRIPTION
**Pull request by karmacharya50**
**Description**

**Screenshots**

**Testing Instructions**

**Contributors**

### CODE REVIEW

**Comment by karmacharya50** [comment]
Added Translation code to the Project details page in the Patterns.

**Comment by karmacharya50** [comment]
Fixed PHPCS errors

**Review by kafleg — APPROVED** [review]
LGTM

**Comment by huzaifaalmesbah** [comment]
> LGTM

Please check [Here](https://github.com/WordPress/twentytwentyfour/pull/308#pullrequestreview-1619407710) before marge.

**Review by richtabor — APPROVED** [review]

**Pull request merged**
