### PR TITLE
Remove image ID from patterns

### PR DESCRIPTION
**Pull request by juanfra**
**Description**

Remove image ID from patterns.

### CODE REVIEW

**Comment by carolinan** [comment]
I think both of these images are supposed to be the avatar block.

**Comment by MaggieCabrera** [comment]
> I think both of these images are supposed to be the avatar block.

Yeah, I think so too

**Comment by juanfra** [comment]
Awesome, I'll update the patterns to use that block then.

**Comment by MaggieCabrera** [comment]
Closing this in favor of https://github.com/WordPress/twentytwentyfour/pull/381

**Pull request closed without merging**
