### PR TITLE
Remove unnecessary spacing

### PR DESCRIPTION
**Pull request by kafleg**
Remove unnecessary spacing from file

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
this needs a rebase

**Comment by kafleg** [comment]
> this needs a rebase

I don't know how we can do that.

**Comment by MaggieCabrera** [comment]
> > this needs a rebase
> 
> I don't know how we can do that.


I don't know what you use for git commands, [this](https://developer.wordpress.org/block-editor/contributors/code/git-workflow/#keeping-your-branch-up-to-date) is how we do it in gutenberg

**Comment by juanfra** [comment]
@kafleg you also have the option of [syncing your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) via web, then merge your trunk branch into your working branch and resolve conflicts locally. 

Or you could also resolve the conflicts via GitHub's UI [here](https://github.com/WordPress/twentytwentyfour/pull/226/conflicts).

Any direction you choose, I suggest you double-check why the files are conflicting and be sure your changes are not overriding any new improvement on them.

**Comment by kafleg** [comment]
> @kafleg you also have the option of [syncing your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) via web, then merge your trunk branch into your working branch and resolve conflicts locally.
> 
> Or you could also resolve the conflicts via GitHub's UI [here](https://github.com/WordPress/twentytwentyfour/pull/226/conflicts).
> 
> Any direction you choose, I suggest you double-check why the files are conflicting and be sure your changes are not overriding any new improvement on them.

Fix the conflicts and merge the commit. Please have a look and thanks for the help.

**Comment by carolinan** [comment]
There still seem to be some unrelated changes? Why are the images and groups duplicated?

**Comment by luminuu** [comment]
Closing this as the spaces have been solved by the latest sync for beta 1.

**Pull request closed without merging**
