### PR TITLE
Updated Centered Statement Pattern

### PR DESCRIPTION
**Pull request by shail-mehta**
**Fixes:**  https://github.com/WordPress/twentytwentyfour/issues/489

### CODE REVIEW

**Comment by beafialho** [comment]
Looks great, thank you!

**Comment by carolinan** [comment]
Is the set pixel height a requirement here? I am asking because there was an effort earlier to replace these values with the presets.

Similarly, there are styles for the paragraphs that  are unnecessary in the markup because they are the default values. These have already been removed from theme at least once.

**Comment by MaggieCabrera** [comment]
> Similarly, there are styles for the paragraphs that are unnecessary in the markup because they are the default values. These have already been removed from theme at least once.

Those are apparently being added by the editor when selecting a color for a paragraph, they appear when copying the markup after doing that, I don´t think Bea is doing anything to the code that the editor is generating.

+1 on the pixels/preset issue, maybe we didn't do a good job selecting the presets that are closer to the design intention?

**Comment by beafialho** [comment]
Can we find a viable solution to have the pattern look like the design?

**Comment by MaggieCabrera** [comment]
I changed the spacer to use the preset 50, which looks almost the same in height as 100px on desktop. I think the rest looks fine and the pattern looks as Bea intended:

Screenshot 2023-09-29 at 11 42 23

@beafialho does this look good to you?

**Comment by beafialho** [comment]
Yes, looks great. Thank you!

**Review by MaggieCabrera — APPROVED** [review]

**Pull request merged**
