### PR TITLE
Update TTF to WOFF2 and Rename Font File Name

### PR DESCRIPTION
**Pull request by huzaifaalmesbah**
I update TTF to WOFF2 and rename font file name

### CODE REVIEW

**Comment by luminuu** [comment]
Is renaming the font files really needed? What benefit does it have?

**Comment by MaggieCabrera** [comment]
> Is renaming the font files really needed? What benefit does it have?

+1, I think it's fine to leave the name as it was, since it shows it's a variable font

**Comment by huzaifaalmesbah** [comment]
> +1, I think it's fine to leave the name as it was, since it shows it's a variable font

**Then we can use like this.**
InstrumentSans-Variable.woff2
InstrumentSans-Italic-Variable.woff2

**Review by luminuu — APPROVED** [review]
Updated the font files to the original names, and fixed the folder for the Jost font, as it was still `instrument-sans`. Fonts are now loading correctly.

**Pull request merged**
