### PR TITLE
Added Left Aligned Call To Action with Image Pattern

### PR DESCRIPTION
**Pull request by chrisdesrochers**
Added Left Aligned Call To Action with Image Pattern per Issue #8 at WCUS. 

I was not able to add checkmarks from the Figma file because there was not a native way to do it with the block editor. I could attempt a Block Style if that's okay for TT4.

### CODE REVIEW

**Review by jeffikus — CHANGES_REQUESTED** [review]
Thank you for your PR! A few things to change before we merge this;

1 - Remove the `inserter: no` line in the comments area
2 - Add the `Category: ` to the comments area
3 - Please make the pattern text translatable by using the `esc_html__` funtion. Here's an example of how to do this, change;
`<li>Showcase your projects</li>`
to 
`<li><?php echo esc_html__( 'Showcase your projects', 'twentytwentyfour' ); ?> </li>`
4 - For the image, the border radius on the corners should be done with the editor.

**Comment by jeffikus** [comment]
I'm fine with adding a block style, we could do that as a separate PR and land this once the above changes have been done.

**Comment by chrisdesrochers** [comment]
@jeffikus I made the fixes requested.

4 - The border radius was set via the editor. See attached screenshot. 
Screenshot 2023-08-24 at 3 01 49 PM

**Comment by chrisdesrochers** [comment]
@jeffikus Everything has been updated (I think) in the branch. For 4, I realized I grabbed the wrong source file from Figma. That's been reuploaded and I updated the pattern file to point to the correct asset.

**Review by jeffikus — APPROVED** [review]
Thanks for making the changes Chris! I made a small typo on the categories, I added the default category into the PR. LGTM!

**Pull request merged**
