### PR TITLE
List custom templates

### PR DESCRIPTION
**Pull request by maneshtimilsina**
- Added a list of custom templates on the `theme.json`

### CODE REVIEW

**Comment by carolinan** [comment]
Hi
I think theme.json should also include the "single-writer" and "single-with-sidebar" templates?

**Comment by maneshtimilsina** [comment]
@carolinan, I have added remaining templates (Single Writer and Single with Sidebar).

**Comment by MaggieCabrera** [comment]
Is there a way to fix the PR so we can see just the lines that you change? the diff is kind of scary :D

**Comment by maneshtimilsina** [comment]
> 

It is difficult to see diff in some cases. There might be a better way but for this file, I have added codes from lines 797 to 854. I think this will help.

**Comment by maneshtimilsina** [comment]
Closing this PR in favor of https://github.com/WordPress/twentytwentyfour/pull/103/

**Pull request closed without merging**
