### PR TITLE
Try rounded group block style

### PR DESCRIPTION
**Pull request by carolinan**
**Description**
border-radius consistency across all patterns by adding a rounded corner block style for groups.
For https://github.com/WordPress/twentytwentyfour/issues/363

**Screenshots**
group with border radius

**Testing Instructions**
Add a group block, and select the block "rounded" block style.

### CODE REVIEW

**Comment by carolinan** [comment]
Opinion: This does not work well without padding and background color.

**Comment by MaggieCabrera** [comment]
I agree with that opinion. Even more so because it's a variation. Let's use the white color from the palette for the background, we've used that style in some of our patterns.

**Comment by carolinan** [comment]
The left and right padding is being overridden by:

```
has-global-padding :where(.has-global-padding:not(.wp-block-block)) {
	padding-right: 0;
	padding-left: 0;
}
```

styled group block is missing left and right padding

**Comment by carolinan** [comment]
I don't think we should use important for the padding to override the styles from core, so I will close this.

**Pull request closed without merging**
