### PR TITLE
add a Neo-Grotesque font stack

### PR DESCRIPTION
**Pull request by LittleBigThing**
Add a Neo-Grotesque (sans-serif) font stack (based on modernfontstacks.com) as a light-weight alternative for Inter

Example implementation of #572

### CODE REVIEW

**Comment by richtabor** [comment]
We should probably name this something more recognizable, like "System font".

**Comment by luminuu** [comment]
There is a PR for adding the true system font: #573 - I'd prefer that one over this PR here, so we don't have too many system fonts cluttering the interface.

**Comment by richtabor** [comment]
Definitely only one. But if we add it to the parent, we'll need it on any variation that overrides fonts I think. Should double-check.

**Comment by luminuu** [comment]
@richtabor Just tested this, we only need to udpate the style variations adding the system fonts if they have fonts declared in the style variation json. If there's no explicit declaration, the fonts from the main `theme.json` are used. Which means Fossil, Ice, Mint and Sandstorm need to be updated. Onyx and Rust need no work.

**Comment by MaggieCabrera** [comment]
Closed in favor of https://github.com/WordPress/twentytwentyfour/pull/667

**Pull request closed without merging**
