### PR TITLE
Add code indentation and escape image links

### PR DESCRIPTION
**Pull request by kishanjasani**
This addresses issue https://github.com/WordPress/twentytwentyfour/issues/65 and adds translation functions to text in the call to action pattern.

### CODE REVIEW

**Comment by carolinan** [comment]
Hi!
Thank you for the update.
The themes use `echo` because each of the example texts needs to have the translator's context added. We did not bother adding that everywhere during the in-person contributor day as people were learning, and the time was limited.

So `esc_html_e()` or `echo esc_html__()` needs to be `echo esc_html_x( 'text', 'context', 'text-domain' )`

Here are examples from Twenty Twenty Three:
```
<!-- wp:paragraph {"style":{"typography":{"lineHeight":"1.2"}},"fontSize":"x-large"} -->
<p class="has-x-large-font-size" style="line-height:1.2"><?php echo esc_html_x( 'Got any book recommendations?', 'sample content for call to action', 'twentytwentythree' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><?php echo esc_html_x( 'This page could not be found.', 'Message to convey that a webpage could not be found', 'twentytwentythree' ); ?></p>
<!-- /wp:paragraph -->

```

**Comment by kishanjasani** [comment]
@carolinan Thanks for the feedback! I will update it with `echo esc_html_x()`.

**Comment by kishanjasani** [comment]
@carolinan Updated the code as per your suggestions. Let me know if I missed something.

**Comment by MaggieCabrera** [comment]
Sadly I think this needs a rebase, are you ok to do this?

**Comment by luminuu** [comment]
I've done it in this branch: https://github.com/WordPress/twentytwentyfour/tree/formate-call-to-action-pattern

**Comment by luminuu** [comment]
@kishanjasani Are you able to update your PR? Otherwise I'd create a new one with your changes there, as I can't update your PR unfortunately.

**Comment by MaggieCabrera** [comment]
> @kishanjasani Are you able to update your PR? Otherwise I'd create a new one with your changes there, as I can't update your PR unfortunately.

@luminuu  I'm going to check your permissions, but I've been able to alter everyone's PRs using [GH cli](https://cli.github.com/manual/gh_pr_checkout)

**Comment by kishanjasani** [comment]
@luminuu I am on it.

**Comment by kishanjasani** [comment]
Hi @luminuu and @MaggieCabrera I have rebase the code. Thanks

**Review by carolinan — APPROVED** [review]
_Note: There are several open pull requests that are updating this file, so some of these changes are likely to be overridden again the next few days._

**Pull request merged**
