### PR TITLE
fix: update footers and apply to templates

### LINKED ISSUE #146: Footer text "Designed with" is not visible.
**Description**
While testing Twenty Twenty Four theme, I found that the Footer text "Designed with" is not visible.

footer-text-not-visible

### PR DESCRIPTION
**Pull request by alaminfirdows**
**Description**

I noticed that the `footer-writer.html` and `footer-portfolio.html` files contain outdated content. Additionally, the `home-portfolio.html` and `home-writer.html` templates are not currently utilizing the template parts. This pull request aims to update both the footers and templates with updated content.

It also fixes the footer text (_Designed with_) visibility issue. 

resolves #146 

**Screenshots**
Screenshot

### CODE REVIEW

**Comment by huzaifaalmesbah** [comment]
You can check #147
already discussed this issue.

**Comment by carolinan** [comment]
Please make sure that:

- The image in the footer is the site logo block
- The social links use the social icon block with the label setting enabled.
- The copyright text uses the site title, not a hard-coded text.
- All text is translation-ready

**Comment by alaminfirdows** [comment]
> You can check #147 already discussed this issue.

@huzaifaalmesbah Thank your for the reference. I've replaced the WordPress credit section by `footer.php` pattern. Please check now.

**Comment by alaminfirdows** [comment]
@carolinan The appearance of the `footer.php` pattern within the footer templates doesn't match the design in Figma.

The pattern has some padding inside. Should we consider removing the padding or perhaps designing a separate pattern for the WordPress credit section?

Group 25

**Comment by carolinan** [comment]
Yeah, try removing the spacing and the text align from the pattern, and re-add those to the template parts.

**Comment by alaminfirdows** [comment]
> Please make sure that:
> 
> * The image in the footer is the site logo block
> * The social links use the social icon block with the label setting enabled.
> * The copyright text uses the site title, not a hard-coded text.
> * All text is translation-ready

Currently the social icon block only support icon+label, it doesn't support the label only.

**Comment by MaggieCabrera** [comment]
Closing this one in favor of https://github.com/WordPress/twentytwentyfour/pull/318

**Pull request closed without merging**
