### PR TITLE
Centered Statement Pattern and adding name to contributor file

### PR DESCRIPTION
**Pull request by ZtMbam**
Centered Statement Pattern and adding name to contributor file

### CODE REVIEW

**Comment by richtabor** [comment]
We're missing the mark a bit here. This is what I'm getting: 

CleanShot 2023-08-28 at 16 50 56

And here's expected ([Figma source](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=565%3A10513&mode=design&t=NgcEssxCEWxthrOW-1)): 

CleanShot 2023-08-28 at 16 52 50

**Comment by carolinan** [comment]
I don't think the columns block is needed, a group with the spacing applied should work.

**Comment by carolinan** [comment]
Hi, I am closing this pull request because someone else submitted the same pattern earlier, so there are duplicate submissions. You will still be added to the contributors list.

**Comment by ZtMbam** [comment]
Thank you so much for this learning opportunity and the chance to contribute to the exceptional WP community! Have a beautiful day! Sent from my iPhoneOn Aug 30, 2023, at 3:01 AM, Carolina Nymark ***@***.***> wrote:﻿
Closed #50.

**Pull request closed without merging**
