### PR TITLE
Block pattern: Business about

### LINKED ISSUE #190: Block pattern: Full page Business About
Let's create a pattern for this page that makes use of all the patterns that we've already created (maybe some are not merged yet, but I think all of them have been started)

Business About

### PR DESCRIPTION
**Pull request by MaggieCabrera**
**Description**

Closes https://github.com/WordPress/twentytwentyfour/issues/190

This pattern includes all the patterns that form the full page one. Some are yet to be merged, but this should work once that's done.

It should also appear on the flow of page creation as an option to select from

### CODE REVIEW

**Comment by richtabor** [comment]
Just noting we don't have the project-details, FAQ, or clients patterns yet — but this is a good base to make sure our patterns are flowing consistently (what https://github.com/WordPress/twentytwentyfour/pull/210 pushes towards).

**Comment by MaggieCabrera** [comment]
yep, but the open PRs for the patterns use those slugs so this will work when those are merged. We can hold this one off until then

**Comment by luminuu** [comment]
I have this one rendering issue in the preview with one of the team images being bigger than the others:

CleanShot 2023-09-05 at 23 21 53@2x

**Comment by richtabor** [comment]
> I have this one rendering issue in the preview with one of the team images being bigger than the others:

Yea that pattern is yet to be revised to fit the design system. 🫣

**Review by scruffian — APPROVED** [review]
I say lets bring this in. It will work once the other patterns merge.

**Pull request merged**
