### PR TITLE
Update comments area

### PR DESCRIPTION
**Pull request by carolinan**
**Description**

Updates the comments area to match the Figma design better.
-Moves the edit link
-Removes default underline on links (shows them on :hover)
-Adds a left border to the nested comments. **We need to consider how we want to solve this for RTL.**

Figma: https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?node-id=507%3A1539&mode=dev

**Screenshots**
Comments area

And with pagination visible:
comment area pagination

**Testing Instructions**
View a single post that has comments.

### CODE REVIEW

**Comment by carolinan** [comment]
The edit and reply link are too close. It may be better to place them inside a row with block spacing, than using the CSS in theme.json.

**Comment by MaggieCabrera** [comment]
I'm happy to skip the border altogether. Using a row block sounds good to me

**Comment by carolinan** [comment]
Without border:
Nested comments without borders

**Comment by carolinan** [comment]
For those who did not follow along with "Blue Note" development;
CSS generated by theme.json is **not** converted for RTL. So a left border would remain on the left side also on RTL, that is why it is problematic and why the easiest solution is to remove it.

**Comment by MaggieCabrera** [comment]
> For those who did not follow along with "Blue Note" development; CSS generated by theme.json is **not** converted for RTL. So a left border would remain on the left side also on RTL, that is why it is problematic and why the easiest solution is to remove it.

I wonder if there should be an alternative CSS for rtl built in from theme.json, is there an open issue in GB?

**Comment by carolinan** [comment]
Yes https://github.com/WordPress/gutenberg/issues/52353

**Review by luminuu — APPROVED** [review]
LGTM!

**Pull request merged**
